/**
 * BusinessSubCategoryType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package eBLBaseComponents.apis.ebay;

public class BusinessSubCategoryType implements java.io.Serializable {
    private org.apache.axis.types.Token _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected BusinessSubCategoryType(org.apache.axis.types.Token value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final org.apache.axis.types.Token _value1 = new org.apache.axis.types.Token("SubCategory-Unspecified");
    public static final org.apache.axis.types.Token _value2 = new org.apache.axis.types.Token("ANTIQUES-General");
    public static final org.apache.axis.types.Token _value3 = new org.apache.axis.types.Token("ANTIQUES-Antiquities");
    public static final org.apache.axis.types.Token _value4 = new org.apache.axis.types.Token("ANTIQUES-Decorative");
    public static final org.apache.axis.types.Token _value5 = new org.apache.axis.types.Token("ANTIQUES-Books-Manuscripts");
    public static final org.apache.axis.types.Token _value6 = new org.apache.axis.types.Token("ANTIQUES-Furniture");
    public static final org.apache.axis.types.Token _value7 = new org.apache.axis.types.Token("ANTIQUES-Glass");
    public static final org.apache.axis.types.Token _value8 = new org.apache.axis.types.Token("ANTIQUES-RugsCarpets");
    public static final org.apache.axis.types.Token _value9 = new org.apache.axis.types.Token("ANTIQUES-Pottery");
    public static final org.apache.axis.types.Token _value10 = new org.apache.axis.types.Token("ANTIQUES-Cultural");
    public static final org.apache.axis.types.Token _value11 = new org.apache.axis.types.Token("ANTIQUES-Artifacts-Grave-related-and-Native-American-Crafts");
    public static final org.apache.axis.types.Token _value12 = new org.apache.axis.types.Token("ARTSANDCRAFTS-General");
    public static final org.apache.axis.types.Token _value13 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Art-Dealer-and-Galleries");
    public static final org.apache.axis.types.Token _value14 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Prints");
    public static final org.apache.axis.types.Token _value15 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Painting");
    public static final org.apache.axis.types.Token _value16 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Photography");
    public static final org.apache.axis.types.Token _value17 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Reproductions");
    public static final org.apache.axis.types.Token _value18 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Sculptures");
    public static final org.apache.axis.types.Token _value19 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Woodworking");
    public static final org.apache.axis.types.Token _value20 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Art-and-Craft-Supplies");
    public static final org.apache.axis.types.Token _value21 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Fabrics-and-Sewing");
    public static final org.apache.axis.types.Token _value22 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Quilting");
    public static final org.apache.axis.types.Token _value23 = new org.apache.axis.types.Token("ARTSANDCRAFTS-Scrapbooking");
    public static final org.apache.axis.types.Token _value24 = new org.apache.axis.types.Token("AUTOMOTIVE-General");
    public static final org.apache.axis.types.Token _value25 = new org.apache.axis.types.Token("AUTOMOTIVE-Autos");
    public static final org.apache.axis.types.Token _value26 = new org.apache.axis.types.Token("AUTOMOTIVE-Aviation");
    public static final org.apache.axis.types.Token _value27 = new org.apache.axis.types.Token("AUTOMOTIVE-Motorcycles");
    public static final org.apache.axis.types.Token _value28 = new org.apache.axis.types.Token("AUTOMOTIVE-Parts-and-Supplies");
    public static final org.apache.axis.types.Token _value29 = new org.apache.axis.types.Token("AUTOMOTIVE-Services");
    public static final org.apache.axis.types.Token _value30 = new org.apache.axis.types.Token("AUTOMOTIVE-Vintage-and-Collectible-Vehicles");
    public static final org.apache.axis.types.Token _value31 = new org.apache.axis.types.Token("BEAUTY-General");
    public static final org.apache.axis.types.Token _value32 = new org.apache.axis.types.Token("BEAUTY-Body-Care-Personal-Hygiene");
    public static final org.apache.axis.types.Token _value33 = new org.apache.axis.types.Token("BEAUTY-Fragrances-and-Perfumes");
    public static final org.apache.axis.types.Token _value34 = new org.apache.axis.types.Token("BEAUTY-Makeup");
    public static final org.apache.axis.types.Token _value35 = new org.apache.axis.types.Token("BOOKS-General");
    public static final org.apache.axis.types.Token _value36 = new org.apache.axis.types.Token("BOOKS-Audio-Books");
    public static final org.apache.axis.types.Token _value37 = new org.apache.axis.types.Token("BOOKS-Children-Books");
    public static final org.apache.axis.types.Token _value38 = new org.apache.axis.types.Token("BOOKS-Computer-Books");
    public static final org.apache.axis.types.Token _value39 = new org.apache.axis.types.Token("BOOKS-Educational-and-Textbooks");
    public static final org.apache.axis.types.Token _value40 = new org.apache.axis.types.Token("BOOKS-Magazines");
    public static final org.apache.axis.types.Token _value41 = new org.apache.axis.types.Token("BOOKS-Fiction-and-Literature");
    public static final org.apache.axis.types.Token _value42 = new org.apache.axis.types.Token("BOOKS-NonFiction");
    public static final org.apache.axis.types.Token _value43 = new org.apache.axis.types.Token("BOOKS-Vintage-and-Collectibles");
    public static final org.apache.axis.types.Token _value44 = new org.apache.axis.types.Token("BUSINESS-General");
    public static final org.apache.axis.types.Token _value45 = new org.apache.axis.types.Token("BUSINESS-Agricultural");
    public static final org.apache.axis.types.Token _value46 = new org.apache.axis.types.Token("BUSINESS-Construction");
    public static final org.apache.axis.types.Token _value47 = new org.apache.axis.types.Token("BUSINESS-Educational");
    public static final org.apache.axis.types.Token _value48 = new org.apache.axis.types.Token("BUSINESS-Industrial");
    public static final org.apache.axis.types.Token _value49 = new org.apache.axis.types.Token("BUSINESS-Office-Supplies-and-Equipment");
    public static final org.apache.axis.types.Token _value50 = new org.apache.axis.types.Token("BUSINESS-GeneralServices");
    public static final org.apache.axis.types.Token _value51 = new org.apache.axis.types.Token("BUSINESS-Advertising");
    public static final org.apache.axis.types.Token _value52 = new org.apache.axis.types.Token("BUSINESS-Employment");
    public static final org.apache.axis.types.Token _value53 = new org.apache.axis.types.Token("BUSINESS-Marketing");
    public static final org.apache.axis.types.Token _value54 = new org.apache.axis.types.Token("BUSINESS-Meeting-Planners");
    public static final org.apache.axis.types.Token _value55 = new org.apache.axis.types.Token("BUSINESS-Messaging-and-Paging-Services");
    public static final org.apache.axis.types.Token _value56 = new org.apache.axis.types.Token("BUSINESS-Seminars");
    public static final org.apache.axis.types.Token _value57 = new org.apache.axis.types.Token("BUSINESS-Publishing");
    public static final org.apache.axis.types.Token _value58 = new org.apache.axis.types.Token("BUSINESS-Shipping-and-Packaging");
    public static final org.apache.axis.types.Token _value59 = new org.apache.axis.types.Token("BUSINESS-Wholesale");
    public static final org.apache.axis.types.Token _value60 = new org.apache.axis.types.Token("BUSINESS-Industrial-Solvents");
    public static final org.apache.axis.types.Token _value61 = new org.apache.axis.types.Token("CAMERASANDPHOTOGRAPHY-General");
    public static final org.apache.axis.types.Token _value62 = new org.apache.axis.types.Token("CAMERASANDPHOTOGRAPHY-Accessories");
    public static final org.apache.axis.types.Token _value63 = new org.apache.axis.types.Token("CAMERASANDPHOTOGRAPHY-Cameras");
    public static final org.apache.axis.types.Token _value64 = new org.apache.axis.types.Token("CAMERASANDPHOTOGRAPHY-Video-Equipment");
    public static final org.apache.axis.types.Token _value65 = new org.apache.axis.types.Token("CAMERASANDPHOTOGRAPHY-Film");
    public static final org.apache.axis.types.Token _value66 = new org.apache.axis.types.Token("CAMERASANDPHOTOGRAPHY-Supplies");
    public static final org.apache.axis.types.Token _value67 = new org.apache.axis.types.Token("CLOTHING-Accessories");
    public static final org.apache.axis.types.Token _value68 = new org.apache.axis.types.Token("CLOTHING-Babies-Clothing-and-Supplies");
    public static final org.apache.axis.types.Token _value69 = new org.apache.axis.types.Token("CLOTHING-Childrens-Clothing");
    public static final org.apache.axis.types.Token _value70 = new org.apache.axis.types.Token("CLOTHING-Mens-Clothing");
    public static final org.apache.axis.types.Token _value71 = new org.apache.axis.types.Token("CLOTHING-Shoes");
    public static final org.apache.axis.types.Token _value72 = new org.apache.axis.types.Token("CLOTHING-Wedding-Clothing");
    public static final org.apache.axis.types.Token _value73 = new org.apache.axis.types.Token("CLOTHING-Womens-Clothing");
    public static final org.apache.axis.types.Token _value74 = new org.apache.axis.types.Token("CLOTHING-General");
    public static final org.apache.axis.types.Token _value75 = new org.apache.axis.types.Token("CLOTHING-Jewelry");
    public static final org.apache.axis.types.Token _value76 = new org.apache.axis.types.Token("CLOTHING-Watches-and-Clocks");
    public static final org.apache.axis.types.Token _value77 = new org.apache.axis.types.Token("CLOTHING-Rings");
    public static final org.apache.axis.types.Token _value78 = new org.apache.axis.types.Token("COLLECTIBLES-General");
    public static final org.apache.axis.types.Token _value79 = new org.apache.axis.types.Token("COLLECTIBLES-Advertising");
    public static final org.apache.axis.types.Token _value80 = new org.apache.axis.types.Token("COLLECTIBLES-Animals");
    public static final org.apache.axis.types.Token _value81 = new org.apache.axis.types.Token("COLLECTIBLES-Animation");
    public static final org.apache.axis.types.Token _value82 = new org.apache.axis.types.Token("COLLECTIBLES-Coin-Operated-Banks-and-Casinos");
    public static final org.apache.axis.types.Token _value83 = new org.apache.axis.types.Token("COLLECTIBLES-Coins-and-Paper-Money");
    public static final org.apache.axis.types.Token _value84 = new org.apache.axis.types.Token("COLLECTIBLES-Comics");
    public static final org.apache.axis.types.Token _value85 = new org.apache.axis.types.Token("COLLECTIBLES-Decorative");
    public static final org.apache.axis.types.Token _value86 = new org.apache.axis.types.Token("COLLECTIBLES-Disneyana");
    public static final org.apache.axis.types.Token _value87 = new org.apache.axis.types.Token("COLLECTIBLES-Holiday");
    public static final org.apache.axis.types.Token _value88 = new org.apache.axis.types.Token("COLLECTIBLES-Knives-and-Swords");
    public static final org.apache.axis.types.Token _value89 = new org.apache.axis.types.Token("COLLECTIBLES-Militaria");
    public static final org.apache.axis.types.Token _value90 = new org.apache.axis.types.Token("COLLECTIBLES-Postcards-and-Paper");
    public static final org.apache.axis.types.Token _value91 = new org.apache.axis.types.Token("COLLECTIBLES-Stamps");
    public static final org.apache.axis.types.Token _value92 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-General");
    public static final org.apache.axis.types.Token _value93 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Desktop-PCs");
    public static final org.apache.axis.types.Token _value94 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Monitors");
    public static final org.apache.axis.types.Token _value95 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Hardware");
    public static final org.apache.axis.types.Token _value96 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Peripherals");
    public static final org.apache.axis.types.Token _value97 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Laptops-Notebooks-PDAs");
    public static final org.apache.axis.types.Token _value98 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Networking-Equipment");
    public static final org.apache.axis.types.Token _value99 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Parts-and-Accessories");
    public static final org.apache.axis.types.Token _value100 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-GeneralSoftware");
    public static final org.apache.axis.types.Token _value101 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Oem-Software");
    public static final org.apache.axis.types.Token _value102 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Academic-Software");
    public static final org.apache.axis.types.Token _value103 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Beta-Software");
    public static final org.apache.axis.types.Token _value104 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Game-Software");
    public static final org.apache.axis.types.Token _value105 = new org.apache.axis.types.Token("COMPUTERHARDWAREANDSOFTWARE-Data-Processing-Svc");
    public static final org.apache.axis.types.Token _value106 = new org.apache.axis.types.Token("CULTUREANDRELIGION-General");
    public static final org.apache.axis.types.Token _value107 = new org.apache.axis.types.Token("CULTUREANDRELIGION-Christianity");
    public static final org.apache.axis.types.Token _value108 = new org.apache.axis.types.Token("CULTUREANDRELIGION-Metaphysical");
    public static final org.apache.axis.types.Token _value109 = new org.apache.axis.types.Token("CULTUREANDRELIGION-New-Age");
    public static final org.apache.axis.types.Token _value110 = new org.apache.axis.types.Token("CULTUREANDRELIGION-Organizations");
    public static final org.apache.axis.types.Token _value111 = new org.apache.axis.types.Token("CULTUREANDRELIGION-Other-Faiths");
    public static final org.apache.axis.types.Token _value112 = new org.apache.axis.types.Token("CULTUREANDRELIGION-Collectibles");
    public static final org.apache.axis.types.Token _value113 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-GeneralTelecom");
    public static final org.apache.axis.types.Token _value114 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Cell-Phones-and-Pagers");
    public static final org.apache.axis.types.Token _value115 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Telephone-Cards");
    public static final org.apache.axis.types.Token _value116 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Telephone-Equipment");
    public static final org.apache.axis.types.Token _value117 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Telephone-Services");
    public static final org.apache.axis.types.Token _value118 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-GeneralElectronics");
    public static final org.apache.axis.types.Token _value119 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Car-Audio-and-Electronics");
    public static final org.apache.axis.types.Token _value120 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Home-Electronics");
    public static final org.apache.axis.types.Token _value121 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Home-Audio");
    public static final org.apache.axis.types.Token _value122 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Gadgets-and-other-electronics");
    public static final org.apache.axis.types.Token _value123 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Batteries");
    public static final org.apache.axis.types.Token _value124 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-ScannersRadios");
    public static final org.apache.axis.types.Token _value125 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Radar-Dectors");
    public static final org.apache.axis.types.Token _value126 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Radar-Jamming-Devices");
    public static final org.apache.axis.types.Token _value127 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Satellite-and-Cable-TV-Descramblers");
    public static final org.apache.axis.types.Token _value128 = new org.apache.axis.types.Token("ELECTRONICSANDTELECOM-Surveillance-Equipment");
    public static final org.apache.axis.types.Token _value129 = new org.apache.axis.types.Token("ENTERTAINMENT-General");
    public static final org.apache.axis.types.Token _value130 = new org.apache.axis.types.Token("ENTERTAINMENT-Movies");
    public static final org.apache.axis.types.Token _value131 = new org.apache.axis.types.Token("ENTERTAINMENT-Music");
    public static final org.apache.axis.types.Token _value132 = new org.apache.axis.types.Token("ENTERTAINMENT-Concerts");
    public static final org.apache.axis.types.Token _value133 = new org.apache.axis.types.Token("ENTERTAINMENT-Theater");
    public static final org.apache.axis.types.Token _value134 = new org.apache.axis.types.Token("ENTERTAINMENT-Bootleg-Recordings");
    public static final org.apache.axis.types.Token _value135 = new org.apache.axis.types.Token("ENTERTAINMENT-Promotional-Items");
    public static final org.apache.axis.types.Token _value136 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-General");
    public static final org.apache.axis.types.Token _value137 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Autographs");
    public static final org.apache.axis.types.Token _value138 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Limited-Editions");
    public static final org.apache.axis.types.Token _value139 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Movie");
    public static final org.apache.axis.types.Token _value140 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Music");
    public static final org.apache.axis.types.Token _value141 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Novelties");
    public static final org.apache.axis.types.Token _value142 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Photos");
    public static final org.apache.axis.types.Token _value143 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Posters");
    public static final org.apache.axis.types.Token _value144 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Sports-and-Fan-Shop");
    public static final org.apache.axis.types.Token _value145 = new org.apache.axis.types.Token("ENTERTAINMENTMEMORABILIA-Science-Fiction");
    public static final org.apache.axis.types.Token _value146 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-General");
    public static final org.apache.axis.types.Token _value147 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Coffee-and-Tea");
    public static final org.apache.axis.types.Token _value148 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Food-Products");
    public static final org.apache.axis.types.Token _value149 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Gourmet-Items");
    public static final org.apache.axis.types.Token _value150 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Health-and-Nutrition");
    public static final org.apache.axis.types.Token _value151 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Services");
    public static final org.apache.axis.types.Token _value152 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Vitamins-and-Supplements");
    public static final org.apache.axis.types.Token _value153 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Weight-Management-and-Health-Products");
    public static final org.apache.axis.types.Token _value154 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Restaurant");
    public static final org.apache.axis.types.Token _value155 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Tobacco-and-Cigars");
    public static final org.apache.axis.types.Token _value156 = new org.apache.axis.types.Token("FOODDRINKANDNUTRITION-Alcoholic-Beverages");
    public static final org.apache.axis.types.Token _value157 = new org.apache.axis.types.Token("GIFTSANDFLOWERS-General");
    public static final org.apache.axis.types.Token _value158 = new org.apache.axis.types.Token("GIFTSANDFLOWERS-Flowers");
    public static final org.apache.axis.types.Token _value159 = new org.apache.axis.types.Token("GIFTSANDFLOWERS-Greeting-Cards");
    public static final org.apache.axis.types.Token _value160 = new org.apache.axis.types.Token("GIFTSANDFLOWERS-Humorous-Gifts-and-Novelties");
    public static final org.apache.axis.types.Token _value161 = new org.apache.axis.types.Token("GIFTSANDFLOWERS-Personalized-Gifts");
    public static final org.apache.axis.types.Token _value162 = new org.apache.axis.types.Token("GIFTSANDFLOWERS-Products");
    public static final org.apache.axis.types.Token _value163 = new org.apache.axis.types.Token("GIFTSANDFLOWERS-Services");
    public static final org.apache.axis.types.Token _value164 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-General");
    public static final org.apache.axis.types.Token _value165 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Action-Figures");
    public static final org.apache.axis.types.Token _value166 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Bean-Babies");
    public static final org.apache.axis.types.Token _value167 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Barbies");
    public static final org.apache.axis.types.Token _value168 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Bears");
    public static final org.apache.axis.types.Token _value169 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Dolls");
    public static final org.apache.axis.types.Token _value170 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Games");
    public static final org.apache.axis.types.Token _value171 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Model-Kits");
    public static final org.apache.axis.types.Token _value172 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Diecast-Toys-Vehicles");
    public static final org.apache.axis.types.Token _value173 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Video-Games-and-Systems");
    public static final org.apache.axis.types.Token _value174 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Vintage-and-Antique-Toys");
    public static final org.apache.axis.types.Token _value175 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-BackupUnreleased-Games");
    public static final org.apache.axis.types.Token _value176 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Game-copying-hardwaresoftware");
    public static final org.apache.axis.types.Token _value177 = new org.apache.axis.types.Token("HOBBIESTOYSANDGAMES-Mod-Chips");
    public static final org.apache.axis.types.Token _value178 = new org.apache.axis.types.Token("HOMEANDGARDEN-General");
    public static final org.apache.axis.types.Token _value179 = new org.apache.axis.types.Token("HOMEANDGARDEN-Appliances");
    public static final org.apache.axis.types.Token _value180 = new org.apache.axis.types.Token("HOMEANDGARDEN-Bed-and-Bath");
    public static final org.apache.axis.types.Token _value181 = new org.apache.axis.types.Token("HOMEANDGARDEN-Furnishing-and-Decorating");
    public static final org.apache.axis.types.Token _value182 = new org.apache.axis.types.Token("HOMEANDGARDEN-Garden-Supplies");
    public static final org.apache.axis.types.Token _value183 = new org.apache.axis.types.Token("HOMEANDGARDEN-Hardware-and-Tools");
    public static final org.apache.axis.types.Token _value184 = new org.apache.axis.types.Token("HOMEANDGARDEN-Household-Goods");
    public static final org.apache.axis.types.Token _value185 = new org.apache.axis.types.Token("HOMEANDGARDEN-Kitchenware");
    public static final org.apache.axis.types.Token _value186 = new org.apache.axis.types.Token("HOMEANDGARDEN-Rugs-and-Carpets");
    public static final org.apache.axis.types.Token _value187 = new org.apache.axis.types.Token("HOMEANDGARDEN-Security-and-Home-Defense");
    public static final org.apache.axis.types.Token _value188 = new org.apache.axis.types.Token("HOMEANDGARDEN-Plants-and-Seeds");
    public static final org.apache.axis.types.Token _value189 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-General");
    public static final org.apache.axis.types.Token _value190 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-Bulletin-board");
    public static final org.apache.axis.types.Token _value191 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-online-services");
    public static final org.apache.axis.types.Token _value192 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-Auction-management-tools");
    public static final org.apache.axis.types.Token _value193 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-ecommerce-development");
    public static final org.apache.axis.types.Token _value194 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-training-services");
    public static final org.apache.axis.types.Token _value195 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-Online-Malls");
    public static final org.apache.axis.types.Token _value196 = new org.apache.axis.types.Token("INTERNETANDNETWORKSERVICES-Web-hosting-and-design");
    public static final org.apache.axis.types.Token _value197 = new org.apache.axis.types.Token("MEDIAANDENTERTAINMENT-General");
    public static final org.apache.axis.types.Token _value198 = new org.apache.axis.types.Token("MEDIAANDENTERTAINMENT-Concerts");
    public static final org.apache.axis.types.Token _value199 = new org.apache.axis.types.Token("MEDIAANDENTERTAINMENT-Theater");
    public static final org.apache.axis.types.Token _value200 = new org.apache.axis.types.Token("MEDICALANDPHARMACEUTICAL-General");
    public static final org.apache.axis.types.Token _value201 = new org.apache.axis.types.Token("MEDICALANDPHARMACEUTICAL-Medical");
    public static final org.apache.axis.types.Token _value202 = new org.apache.axis.types.Token("MEDICALANDPHARMACEUTICAL-Dental");
    public static final org.apache.axis.types.Token _value203 = new org.apache.axis.types.Token("MEDICALANDPHARMACEUTICAL-Opthamalic");
    public static final org.apache.axis.types.Token _value204 = new org.apache.axis.types.Token("MEDICALANDPHARMACEUTICAL-Prescription-Drugs");
    public static final org.apache.axis.types.Token _value205 = new org.apache.axis.types.Token("MEDICALANDPHARMACEUTICAL-Devices");
    public static final org.apache.axis.types.Token _value206 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-General");
    public static final org.apache.axis.types.Token _value207 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Remittance");
    public static final org.apache.axis.types.Token _value208 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Wire-Transfer");
    public static final org.apache.axis.types.Token _value209 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Money-Orders");
    public static final org.apache.axis.types.Token _value210 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Electronic-Cash");
    public static final org.apache.axis.types.Token _value211 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Currency-DealerExchange");
    public static final org.apache.axis.types.Token _value212 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Check-Cashier");
    public static final org.apache.axis.types.Token _value213 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Travelers-Checks");
    public static final org.apache.axis.types.Token _value214 = new org.apache.axis.types.Token("MONEYSERVICEBUSINESSES-Stored-Value-Cards");
    public static final org.apache.axis.types.Token _value215 = new org.apache.axis.types.Token("NONPROFITPOLITICALANDRELIGION-General");
    public static final org.apache.axis.types.Token _value216 = new org.apache.axis.types.Token("NONPROFITPOLITICALANDRELIGION-Charities");
    public static final org.apache.axis.types.Token _value217 = new org.apache.axis.types.Token("NONPROFITPOLITICALANDRELIGION-Political");
    public static final org.apache.axis.types.Token _value218 = new org.apache.axis.types.Token("NONPROFITPOLITICALANDRELIGION-Religious");
    public static final org.apache.axis.types.Token _value219 = new org.apache.axis.types.Token("PETSANDANIMALS-General");
    public static final org.apache.axis.types.Token _value220 = new org.apache.axis.types.Token("PETSANDANIMALS-Supplies-and-Toys");
    public static final org.apache.axis.types.Token _value221 = new org.apache.axis.types.Token("PETSANDANIMALS-Wildlife-Products");
    public static final org.apache.axis.types.Token _value222 = new org.apache.axis.types.Token("REALESTATE-General");
    public static final org.apache.axis.types.Token _value223 = new org.apache.axis.types.Token("REALESTATE-Commercial");
    public static final org.apache.axis.types.Token _value224 = new org.apache.axis.types.Token("REALESTATE-Residential");
    public static final org.apache.axis.types.Token _value225 = new org.apache.axis.types.Token("REALESTATE-Time-Shares");
    public static final org.apache.axis.types.Token _value226 = new org.apache.axis.types.Token("SERVICES-GeneralGovernment");
    public static final org.apache.axis.types.Token _value227 = new org.apache.axis.types.Token("SERVICES-Legal");
    public static final org.apache.axis.types.Token _value228 = new org.apache.axis.types.Token("SERVICES-Medical");
    public static final org.apache.axis.types.Token _value229 = new org.apache.axis.types.Token("SERVICES-Dental");
    public static final org.apache.axis.types.Token _value230 = new org.apache.axis.types.Token("SERVICES-Vision");
    public static final org.apache.axis.types.Token _value231 = new org.apache.axis.types.Token("SERVICES-General");
    public static final org.apache.axis.types.Token _value232 = new org.apache.axis.types.Token("SERVICES-Child-Care-Services");
    public static final org.apache.axis.types.Token _value233 = new org.apache.axis.types.Token("SERVICES-Consulting");
    public static final org.apache.axis.types.Token _value234 = new org.apache.axis.types.Token("SERVICES-ImportingExporting");
    public static final org.apache.axis.types.Token _value235 = new org.apache.axis.types.Token("SERVICES-InsuranceDirect");
    public static final org.apache.axis.types.Token _value236 = new org.apache.axis.types.Token("SERVICES-Financial-Services");
    public static final org.apache.axis.types.Token _value237 = new org.apache.axis.types.Token("SERVICES-Graphic-and-Commercial-Design");
    public static final org.apache.axis.types.Token _value238 = new org.apache.axis.types.Token("SERVICES-Landscaping");
    public static final org.apache.axis.types.Token _value239 = new org.apache.axis.types.Token("SERVICES-Locksmith");
    public static final org.apache.axis.types.Token _value240 = new org.apache.axis.types.Token("SERVICES-Online-Dating");
    public static final org.apache.axis.types.Token _value241 = new org.apache.axis.types.Token("SERVICES-Event-and-Wedding-Planning");
    public static final org.apache.axis.types.Token _value242 = new org.apache.axis.types.Token("SERVICES-Schools-and-Colleges");
    public static final org.apache.axis.types.Token _value243 = new org.apache.axis.types.Token("SERVICES-Entertainment");
    public static final org.apache.axis.types.Token _value244 = new org.apache.axis.types.Token("SERVICES-Aggregators");
    public static final org.apache.axis.types.Token _value245 = new org.apache.axis.types.Token("SPORTSANDRECREATION-General");
    public static final org.apache.axis.types.Token _value246 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Bicycles-and-Accessories");
    public static final org.apache.axis.types.Token _value247 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Boating-Sailing-and-Accessories");
    public static final org.apache.axis.types.Token _value248 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Camping-and-Survival");
    public static final org.apache.axis.types.Token _value249 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Exercise-Equipment");
    public static final org.apache.axis.types.Token _value250 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Fishing");
    public static final org.apache.axis.types.Token _value251 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Golf");
    public static final org.apache.axis.types.Token _value252 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Hunting");
    public static final org.apache.axis.types.Token _value253 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Paintball");
    public static final org.apache.axis.types.Token _value254 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Sporting-Goods");
    public static final org.apache.axis.types.Token _value255 = new org.apache.axis.types.Token("SPORTSANDRECREATION-Swimming-Pools-and-Spas");
    public static final org.apache.axis.types.Token _value256 = new org.apache.axis.types.Token("TRAVEL-General");
    public static final org.apache.axis.types.Token _value257 = new org.apache.axis.types.Token("TRAVEL-Accommodations");
    public static final org.apache.axis.types.Token _value258 = new org.apache.axis.types.Token("TRAVEL-Agencies");
    public static final org.apache.axis.types.Token _value259 = new org.apache.axis.types.Token("TRAVEL-Airlines");
    public static final org.apache.axis.types.Token _value260 = new org.apache.axis.types.Token("TRAVEL-Auto-Rentals");
    public static final org.apache.axis.types.Token _value261 = new org.apache.axis.types.Token("TRAVEL-Cruises");
    public static final org.apache.axis.types.Token _value262 = new org.apache.axis.types.Token("TRAVEL-Other-Transportation");
    public static final org.apache.axis.types.Token _value263 = new org.apache.axis.types.Token("TRAVEL-Services");
    public static final org.apache.axis.types.Token _value264 = new org.apache.axis.types.Token("TRAVEL-Supplies");
    public static final org.apache.axis.types.Token _value265 = new org.apache.axis.types.Token("TRAVEL-Tours");
    public static final org.apache.axis.types.Token _value266 = new org.apache.axis.types.Token("TRAVEL-AirlinesSpirit-Air");
    public static final org.apache.axis.types.Token _value267 = new org.apache.axis.types.Token("Other-SubCategories");
    public static final BusinessSubCategoryType value1 = new BusinessSubCategoryType(_value1);
    public static final BusinessSubCategoryType value2 = new BusinessSubCategoryType(_value2);
    public static final BusinessSubCategoryType value3 = new BusinessSubCategoryType(_value3);
    public static final BusinessSubCategoryType value4 = new BusinessSubCategoryType(_value4);
    public static final BusinessSubCategoryType value5 = new BusinessSubCategoryType(_value5);
    public static final BusinessSubCategoryType value6 = new BusinessSubCategoryType(_value6);
    public static final BusinessSubCategoryType value7 = new BusinessSubCategoryType(_value7);
    public static final BusinessSubCategoryType value8 = new BusinessSubCategoryType(_value8);
    public static final BusinessSubCategoryType value9 = new BusinessSubCategoryType(_value9);
    public static final BusinessSubCategoryType value10 = new BusinessSubCategoryType(_value10);
    public static final BusinessSubCategoryType value11 = new BusinessSubCategoryType(_value11);
    public static final BusinessSubCategoryType value12 = new BusinessSubCategoryType(_value12);
    public static final BusinessSubCategoryType value13 = new BusinessSubCategoryType(_value13);
    public static final BusinessSubCategoryType value14 = new BusinessSubCategoryType(_value14);
    public static final BusinessSubCategoryType value15 = new BusinessSubCategoryType(_value15);
    public static final BusinessSubCategoryType value16 = new BusinessSubCategoryType(_value16);
    public static final BusinessSubCategoryType value17 = new BusinessSubCategoryType(_value17);
    public static final BusinessSubCategoryType value18 = new BusinessSubCategoryType(_value18);
    public static final BusinessSubCategoryType value19 = new BusinessSubCategoryType(_value19);
    public static final BusinessSubCategoryType value20 = new BusinessSubCategoryType(_value20);
    public static final BusinessSubCategoryType value21 = new BusinessSubCategoryType(_value21);
    public static final BusinessSubCategoryType value22 = new BusinessSubCategoryType(_value22);
    public static final BusinessSubCategoryType value23 = new BusinessSubCategoryType(_value23);
    public static final BusinessSubCategoryType value24 = new BusinessSubCategoryType(_value24);
    public static final BusinessSubCategoryType value25 = new BusinessSubCategoryType(_value25);
    public static final BusinessSubCategoryType value26 = new BusinessSubCategoryType(_value26);
    public static final BusinessSubCategoryType value27 = new BusinessSubCategoryType(_value27);
    public static final BusinessSubCategoryType value28 = new BusinessSubCategoryType(_value28);
    public static final BusinessSubCategoryType value29 = new BusinessSubCategoryType(_value29);
    public static final BusinessSubCategoryType value30 = new BusinessSubCategoryType(_value30);
    public static final BusinessSubCategoryType value31 = new BusinessSubCategoryType(_value31);
    public static final BusinessSubCategoryType value32 = new BusinessSubCategoryType(_value32);
    public static final BusinessSubCategoryType value33 = new BusinessSubCategoryType(_value33);
    public static final BusinessSubCategoryType value34 = new BusinessSubCategoryType(_value34);
    public static final BusinessSubCategoryType value35 = new BusinessSubCategoryType(_value35);
    public static final BusinessSubCategoryType value36 = new BusinessSubCategoryType(_value36);
    public static final BusinessSubCategoryType value37 = new BusinessSubCategoryType(_value37);
    public static final BusinessSubCategoryType value38 = new BusinessSubCategoryType(_value38);
    public static final BusinessSubCategoryType value39 = new BusinessSubCategoryType(_value39);
    public static final BusinessSubCategoryType value40 = new BusinessSubCategoryType(_value40);
    public static final BusinessSubCategoryType value41 = new BusinessSubCategoryType(_value41);
    public static final BusinessSubCategoryType value42 = new BusinessSubCategoryType(_value42);
    public static final BusinessSubCategoryType value43 = new BusinessSubCategoryType(_value43);
    public static final BusinessSubCategoryType value44 = new BusinessSubCategoryType(_value44);
    public static final BusinessSubCategoryType value45 = new BusinessSubCategoryType(_value45);
    public static final BusinessSubCategoryType value46 = new BusinessSubCategoryType(_value46);
    public static final BusinessSubCategoryType value47 = new BusinessSubCategoryType(_value47);
    public static final BusinessSubCategoryType value48 = new BusinessSubCategoryType(_value48);
    public static final BusinessSubCategoryType value49 = new BusinessSubCategoryType(_value49);
    public static final BusinessSubCategoryType value50 = new BusinessSubCategoryType(_value50);
    public static final BusinessSubCategoryType value51 = new BusinessSubCategoryType(_value51);
    public static final BusinessSubCategoryType value52 = new BusinessSubCategoryType(_value52);
    public static final BusinessSubCategoryType value53 = new BusinessSubCategoryType(_value53);
    public static final BusinessSubCategoryType value54 = new BusinessSubCategoryType(_value54);
    public static final BusinessSubCategoryType value55 = new BusinessSubCategoryType(_value55);
    public static final BusinessSubCategoryType value56 = new BusinessSubCategoryType(_value56);
    public static final BusinessSubCategoryType value57 = new BusinessSubCategoryType(_value57);
    public static final BusinessSubCategoryType value58 = new BusinessSubCategoryType(_value58);
    public static final BusinessSubCategoryType value59 = new BusinessSubCategoryType(_value59);
    public static final BusinessSubCategoryType value60 = new BusinessSubCategoryType(_value60);
    public static final BusinessSubCategoryType value61 = new BusinessSubCategoryType(_value61);
    public static final BusinessSubCategoryType value62 = new BusinessSubCategoryType(_value62);
    public static final BusinessSubCategoryType value63 = new BusinessSubCategoryType(_value63);
    public static final BusinessSubCategoryType value64 = new BusinessSubCategoryType(_value64);
    public static final BusinessSubCategoryType value65 = new BusinessSubCategoryType(_value65);
    public static final BusinessSubCategoryType value66 = new BusinessSubCategoryType(_value66);
    public static final BusinessSubCategoryType value67 = new BusinessSubCategoryType(_value67);
    public static final BusinessSubCategoryType value68 = new BusinessSubCategoryType(_value68);
    public static final BusinessSubCategoryType value69 = new BusinessSubCategoryType(_value69);
    public static final BusinessSubCategoryType value70 = new BusinessSubCategoryType(_value70);
    public static final BusinessSubCategoryType value71 = new BusinessSubCategoryType(_value71);
    public static final BusinessSubCategoryType value72 = new BusinessSubCategoryType(_value72);
    public static final BusinessSubCategoryType value73 = new BusinessSubCategoryType(_value73);
    public static final BusinessSubCategoryType value74 = new BusinessSubCategoryType(_value74);
    public static final BusinessSubCategoryType value75 = new BusinessSubCategoryType(_value75);
    public static final BusinessSubCategoryType value76 = new BusinessSubCategoryType(_value76);
    public static final BusinessSubCategoryType value77 = new BusinessSubCategoryType(_value77);
    public static final BusinessSubCategoryType value78 = new BusinessSubCategoryType(_value78);
    public static final BusinessSubCategoryType value79 = new BusinessSubCategoryType(_value79);
    public static final BusinessSubCategoryType value80 = new BusinessSubCategoryType(_value80);
    public static final BusinessSubCategoryType value81 = new BusinessSubCategoryType(_value81);
    public static final BusinessSubCategoryType value82 = new BusinessSubCategoryType(_value82);
    public static final BusinessSubCategoryType value83 = new BusinessSubCategoryType(_value83);
    public static final BusinessSubCategoryType value84 = new BusinessSubCategoryType(_value84);
    public static final BusinessSubCategoryType value85 = new BusinessSubCategoryType(_value85);
    public static final BusinessSubCategoryType value86 = new BusinessSubCategoryType(_value86);
    public static final BusinessSubCategoryType value87 = new BusinessSubCategoryType(_value87);
    public static final BusinessSubCategoryType value88 = new BusinessSubCategoryType(_value88);
    public static final BusinessSubCategoryType value89 = new BusinessSubCategoryType(_value89);
    public static final BusinessSubCategoryType value90 = new BusinessSubCategoryType(_value90);
    public static final BusinessSubCategoryType value91 = new BusinessSubCategoryType(_value91);
    public static final BusinessSubCategoryType value92 = new BusinessSubCategoryType(_value92);
    public static final BusinessSubCategoryType value93 = new BusinessSubCategoryType(_value93);
    public static final BusinessSubCategoryType value94 = new BusinessSubCategoryType(_value94);
    public static final BusinessSubCategoryType value95 = new BusinessSubCategoryType(_value95);
    public static final BusinessSubCategoryType value96 = new BusinessSubCategoryType(_value96);
    public static final BusinessSubCategoryType value97 = new BusinessSubCategoryType(_value97);
    public static final BusinessSubCategoryType value98 = new BusinessSubCategoryType(_value98);
    public static final BusinessSubCategoryType value99 = new BusinessSubCategoryType(_value99);
    public static final BusinessSubCategoryType value100 = new BusinessSubCategoryType(_value100);
    public static final BusinessSubCategoryType value101 = new BusinessSubCategoryType(_value101);
    public static final BusinessSubCategoryType value102 = new BusinessSubCategoryType(_value102);
    public static final BusinessSubCategoryType value103 = new BusinessSubCategoryType(_value103);
    public static final BusinessSubCategoryType value104 = new BusinessSubCategoryType(_value104);
    public static final BusinessSubCategoryType value105 = new BusinessSubCategoryType(_value105);
    public static final BusinessSubCategoryType value106 = new BusinessSubCategoryType(_value106);
    public static final BusinessSubCategoryType value107 = new BusinessSubCategoryType(_value107);
    public static final BusinessSubCategoryType value108 = new BusinessSubCategoryType(_value108);
    public static final BusinessSubCategoryType value109 = new BusinessSubCategoryType(_value109);
    public static final BusinessSubCategoryType value110 = new BusinessSubCategoryType(_value110);
    public static final BusinessSubCategoryType value111 = new BusinessSubCategoryType(_value111);
    public static final BusinessSubCategoryType value112 = new BusinessSubCategoryType(_value112);
    public static final BusinessSubCategoryType value113 = new BusinessSubCategoryType(_value113);
    public static final BusinessSubCategoryType value114 = new BusinessSubCategoryType(_value114);
    public static final BusinessSubCategoryType value115 = new BusinessSubCategoryType(_value115);
    public static final BusinessSubCategoryType value116 = new BusinessSubCategoryType(_value116);
    public static final BusinessSubCategoryType value117 = new BusinessSubCategoryType(_value117);
    public static final BusinessSubCategoryType value118 = new BusinessSubCategoryType(_value118);
    public static final BusinessSubCategoryType value119 = new BusinessSubCategoryType(_value119);
    public static final BusinessSubCategoryType value120 = new BusinessSubCategoryType(_value120);
    public static final BusinessSubCategoryType value121 = new BusinessSubCategoryType(_value121);
    public static final BusinessSubCategoryType value122 = new BusinessSubCategoryType(_value122);
    public static final BusinessSubCategoryType value123 = new BusinessSubCategoryType(_value123);
    public static final BusinessSubCategoryType value124 = new BusinessSubCategoryType(_value124);
    public static final BusinessSubCategoryType value125 = new BusinessSubCategoryType(_value125);
    public static final BusinessSubCategoryType value126 = new BusinessSubCategoryType(_value126);
    public static final BusinessSubCategoryType value127 = new BusinessSubCategoryType(_value127);
    public static final BusinessSubCategoryType value128 = new BusinessSubCategoryType(_value128);
    public static final BusinessSubCategoryType value129 = new BusinessSubCategoryType(_value129);
    public static final BusinessSubCategoryType value130 = new BusinessSubCategoryType(_value130);
    public static final BusinessSubCategoryType value131 = new BusinessSubCategoryType(_value131);
    public static final BusinessSubCategoryType value132 = new BusinessSubCategoryType(_value132);
    public static final BusinessSubCategoryType value133 = new BusinessSubCategoryType(_value133);
    public static final BusinessSubCategoryType value134 = new BusinessSubCategoryType(_value134);
    public static final BusinessSubCategoryType value135 = new BusinessSubCategoryType(_value135);
    public static final BusinessSubCategoryType value136 = new BusinessSubCategoryType(_value136);
    public static final BusinessSubCategoryType value137 = new BusinessSubCategoryType(_value137);
    public static final BusinessSubCategoryType value138 = new BusinessSubCategoryType(_value138);
    public static final BusinessSubCategoryType value139 = new BusinessSubCategoryType(_value139);
    public static final BusinessSubCategoryType value140 = new BusinessSubCategoryType(_value140);
    public static final BusinessSubCategoryType value141 = new BusinessSubCategoryType(_value141);
    public static final BusinessSubCategoryType value142 = new BusinessSubCategoryType(_value142);
    public static final BusinessSubCategoryType value143 = new BusinessSubCategoryType(_value143);
    public static final BusinessSubCategoryType value144 = new BusinessSubCategoryType(_value144);
    public static final BusinessSubCategoryType value145 = new BusinessSubCategoryType(_value145);
    public static final BusinessSubCategoryType value146 = new BusinessSubCategoryType(_value146);
    public static final BusinessSubCategoryType value147 = new BusinessSubCategoryType(_value147);
    public static final BusinessSubCategoryType value148 = new BusinessSubCategoryType(_value148);
    public static final BusinessSubCategoryType value149 = new BusinessSubCategoryType(_value149);
    public static final BusinessSubCategoryType value150 = new BusinessSubCategoryType(_value150);
    public static final BusinessSubCategoryType value151 = new BusinessSubCategoryType(_value151);
    public static final BusinessSubCategoryType value152 = new BusinessSubCategoryType(_value152);
    public static final BusinessSubCategoryType value153 = new BusinessSubCategoryType(_value153);
    public static final BusinessSubCategoryType value154 = new BusinessSubCategoryType(_value154);
    public static final BusinessSubCategoryType value155 = new BusinessSubCategoryType(_value155);
    public static final BusinessSubCategoryType value156 = new BusinessSubCategoryType(_value156);
    public static final BusinessSubCategoryType value157 = new BusinessSubCategoryType(_value157);
    public static final BusinessSubCategoryType value158 = new BusinessSubCategoryType(_value158);
    public static final BusinessSubCategoryType value159 = new BusinessSubCategoryType(_value159);
    public static final BusinessSubCategoryType value160 = new BusinessSubCategoryType(_value160);
    public static final BusinessSubCategoryType value161 = new BusinessSubCategoryType(_value161);
    public static final BusinessSubCategoryType value162 = new BusinessSubCategoryType(_value162);
    public static final BusinessSubCategoryType value163 = new BusinessSubCategoryType(_value163);
    public static final BusinessSubCategoryType value164 = new BusinessSubCategoryType(_value164);
    public static final BusinessSubCategoryType value165 = new BusinessSubCategoryType(_value165);
    public static final BusinessSubCategoryType value166 = new BusinessSubCategoryType(_value166);
    public static final BusinessSubCategoryType value167 = new BusinessSubCategoryType(_value167);
    public static final BusinessSubCategoryType value168 = new BusinessSubCategoryType(_value168);
    public static final BusinessSubCategoryType value169 = new BusinessSubCategoryType(_value169);
    public static final BusinessSubCategoryType value170 = new BusinessSubCategoryType(_value170);
    public static final BusinessSubCategoryType value171 = new BusinessSubCategoryType(_value171);
    public static final BusinessSubCategoryType value172 = new BusinessSubCategoryType(_value172);
    public static final BusinessSubCategoryType value173 = new BusinessSubCategoryType(_value173);
    public static final BusinessSubCategoryType value174 = new BusinessSubCategoryType(_value174);
    public static final BusinessSubCategoryType value175 = new BusinessSubCategoryType(_value175);
    public static final BusinessSubCategoryType value176 = new BusinessSubCategoryType(_value176);
    public static final BusinessSubCategoryType value177 = new BusinessSubCategoryType(_value177);
    public static final BusinessSubCategoryType value178 = new BusinessSubCategoryType(_value178);
    public static final BusinessSubCategoryType value179 = new BusinessSubCategoryType(_value179);
    public static final BusinessSubCategoryType value180 = new BusinessSubCategoryType(_value180);
    public static final BusinessSubCategoryType value181 = new BusinessSubCategoryType(_value181);
    public static final BusinessSubCategoryType value182 = new BusinessSubCategoryType(_value182);
    public static final BusinessSubCategoryType value183 = new BusinessSubCategoryType(_value183);
    public static final BusinessSubCategoryType value184 = new BusinessSubCategoryType(_value184);
    public static final BusinessSubCategoryType value185 = new BusinessSubCategoryType(_value185);
    public static final BusinessSubCategoryType value186 = new BusinessSubCategoryType(_value186);
    public static final BusinessSubCategoryType value187 = new BusinessSubCategoryType(_value187);
    public static final BusinessSubCategoryType value188 = new BusinessSubCategoryType(_value188);
    public static final BusinessSubCategoryType value189 = new BusinessSubCategoryType(_value189);
    public static final BusinessSubCategoryType value190 = new BusinessSubCategoryType(_value190);
    public static final BusinessSubCategoryType value191 = new BusinessSubCategoryType(_value191);
    public static final BusinessSubCategoryType value192 = new BusinessSubCategoryType(_value192);
    public static final BusinessSubCategoryType value193 = new BusinessSubCategoryType(_value193);
    public static final BusinessSubCategoryType value194 = new BusinessSubCategoryType(_value194);
    public static final BusinessSubCategoryType value195 = new BusinessSubCategoryType(_value195);
    public static final BusinessSubCategoryType value196 = new BusinessSubCategoryType(_value196);
    public static final BusinessSubCategoryType value197 = new BusinessSubCategoryType(_value197);
    public static final BusinessSubCategoryType value198 = new BusinessSubCategoryType(_value198);
    public static final BusinessSubCategoryType value199 = new BusinessSubCategoryType(_value199);
    public static final BusinessSubCategoryType value200 = new BusinessSubCategoryType(_value200);
    public static final BusinessSubCategoryType value201 = new BusinessSubCategoryType(_value201);
    public static final BusinessSubCategoryType value202 = new BusinessSubCategoryType(_value202);
    public static final BusinessSubCategoryType value203 = new BusinessSubCategoryType(_value203);
    public static final BusinessSubCategoryType value204 = new BusinessSubCategoryType(_value204);
    public static final BusinessSubCategoryType value205 = new BusinessSubCategoryType(_value205);
    public static final BusinessSubCategoryType value206 = new BusinessSubCategoryType(_value206);
    public static final BusinessSubCategoryType value207 = new BusinessSubCategoryType(_value207);
    public static final BusinessSubCategoryType value208 = new BusinessSubCategoryType(_value208);
    public static final BusinessSubCategoryType value209 = new BusinessSubCategoryType(_value209);
    public static final BusinessSubCategoryType value210 = new BusinessSubCategoryType(_value210);
    public static final BusinessSubCategoryType value211 = new BusinessSubCategoryType(_value211);
    public static final BusinessSubCategoryType value212 = new BusinessSubCategoryType(_value212);
    public static final BusinessSubCategoryType value213 = new BusinessSubCategoryType(_value213);
    public static final BusinessSubCategoryType value214 = new BusinessSubCategoryType(_value214);
    public static final BusinessSubCategoryType value215 = new BusinessSubCategoryType(_value215);
    public static final BusinessSubCategoryType value216 = new BusinessSubCategoryType(_value216);
    public static final BusinessSubCategoryType value217 = new BusinessSubCategoryType(_value217);
    public static final BusinessSubCategoryType value218 = new BusinessSubCategoryType(_value218);
    public static final BusinessSubCategoryType value219 = new BusinessSubCategoryType(_value219);
    public static final BusinessSubCategoryType value220 = new BusinessSubCategoryType(_value220);
    public static final BusinessSubCategoryType value221 = new BusinessSubCategoryType(_value221);
    public static final BusinessSubCategoryType value222 = new BusinessSubCategoryType(_value222);
    public static final BusinessSubCategoryType value223 = new BusinessSubCategoryType(_value223);
    public static final BusinessSubCategoryType value224 = new BusinessSubCategoryType(_value224);
    public static final BusinessSubCategoryType value225 = new BusinessSubCategoryType(_value225);
    public static final BusinessSubCategoryType value226 = new BusinessSubCategoryType(_value226);
    public static final BusinessSubCategoryType value227 = new BusinessSubCategoryType(_value227);
    public static final BusinessSubCategoryType value228 = new BusinessSubCategoryType(_value228);
    public static final BusinessSubCategoryType value229 = new BusinessSubCategoryType(_value229);
    public static final BusinessSubCategoryType value230 = new BusinessSubCategoryType(_value230);
    public static final BusinessSubCategoryType value231 = new BusinessSubCategoryType(_value231);
    public static final BusinessSubCategoryType value232 = new BusinessSubCategoryType(_value232);
    public static final BusinessSubCategoryType value233 = new BusinessSubCategoryType(_value233);
    public static final BusinessSubCategoryType value234 = new BusinessSubCategoryType(_value234);
    public static final BusinessSubCategoryType value235 = new BusinessSubCategoryType(_value235);
    public static final BusinessSubCategoryType value236 = new BusinessSubCategoryType(_value236);
    public static final BusinessSubCategoryType value237 = new BusinessSubCategoryType(_value237);
    public static final BusinessSubCategoryType value238 = new BusinessSubCategoryType(_value238);
    public static final BusinessSubCategoryType value239 = new BusinessSubCategoryType(_value239);
    public static final BusinessSubCategoryType value240 = new BusinessSubCategoryType(_value240);
    public static final BusinessSubCategoryType value241 = new BusinessSubCategoryType(_value241);
    public static final BusinessSubCategoryType value242 = new BusinessSubCategoryType(_value242);
    public static final BusinessSubCategoryType value243 = new BusinessSubCategoryType(_value243);
    public static final BusinessSubCategoryType value244 = new BusinessSubCategoryType(_value244);
    public static final BusinessSubCategoryType value245 = new BusinessSubCategoryType(_value245);
    public static final BusinessSubCategoryType value246 = new BusinessSubCategoryType(_value246);
    public static final BusinessSubCategoryType value247 = new BusinessSubCategoryType(_value247);
    public static final BusinessSubCategoryType value248 = new BusinessSubCategoryType(_value248);
    public static final BusinessSubCategoryType value249 = new BusinessSubCategoryType(_value249);
    public static final BusinessSubCategoryType value250 = new BusinessSubCategoryType(_value250);
    public static final BusinessSubCategoryType value251 = new BusinessSubCategoryType(_value251);
    public static final BusinessSubCategoryType value252 = new BusinessSubCategoryType(_value252);
    public static final BusinessSubCategoryType value253 = new BusinessSubCategoryType(_value253);
    public static final BusinessSubCategoryType value254 = new BusinessSubCategoryType(_value254);
    public static final BusinessSubCategoryType value255 = new BusinessSubCategoryType(_value255);
    public static final BusinessSubCategoryType value256 = new BusinessSubCategoryType(_value256);
    public static final BusinessSubCategoryType value257 = new BusinessSubCategoryType(_value257);
    public static final BusinessSubCategoryType value258 = new BusinessSubCategoryType(_value258);
    public static final BusinessSubCategoryType value259 = new BusinessSubCategoryType(_value259);
    public static final BusinessSubCategoryType value260 = new BusinessSubCategoryType(_value260);
    public static final BusinessSubCategoryType value261 = new BusinessSubCategoryType(_value261);
    public static final BusinessSubCategoryType value262 = new BusinessSubCategoryType(_value262);
    public static final BusinessSubCategoryType value263 = new BusinessSubCategoryType(_value263);
    public static final BusinessSubCategoryType value264 = new BusinessSubCategoryType(_value264);
    public static final BusinessSubCategoryType value265 = new BusinessSubCategoryType(_value265);
    public static final BusinessSubCategoryType value266 = new BusinessSubCategoryType(_value266);
    public static final BusinessSubCategoryType value267 = new BusinessSubCategoryType(_value267);
    public org.apache.axis.types.Token getValue() { return _value_;}
    public static BusinessSubCategoryType fromValue(org.apache.axis.types.Token value)
          throws java.lang.IllegalArgumentException {
        BusinessSubCategoryType enumeration = (BusinessSubCategoryType)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static BusinessSubCategoryType fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        try {
            return fromValue(new org.apache.axis.types.Token(value));
        } catch (Exception e) {
            throw new java.lang.IllegalArgumentException();
        }
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_.toString();}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(BusinessSubCategoryType.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("urn:ebay:apis:eBLBaseComponents", "BusinessSubCategoryType"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
