/**
 * CountryCodeType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package eBLBaseComponents.apis.ebay;

public class CountryCodeType implements java.io.Serializable {
    private org.apache.axis.types.Token _value_;
    private static java.util.HashMap _table_ = new java.util.HashMap();

    // Constructor
    protected CountryCodeType(org.apache.axis.types.Token value) {
        _value_ = value;
        _table_.put(_value_,this);
    }

    public static final org.apache.axis.types.Token _AF = new org.apache.axis.types.Token("AF");
    public static final org.apache.axis.types.Token _AL = new org.apache.axis.types.Token("AL");
    public static final org.apache.axis.types.Token _DZ = new org.apache.axis.types.Token("DZ");
    public static final org.apache.axis.types.Token _AS = new org.apache.axis.types.Token("AS");
    public static final org.apache.axis.types.Token _AD = new org.apache.axis.types.Token("AD");
    public static final org.apache.axis.types.Token _AO = new org.apache.axis.types.Token("AO");
    public static final org.apache.axis.types.Token _AI = new org.apache.axis.types.Token("AI");
    public static final org.apache.axis.types.Token _AQ = new org.apache.axis.types.Token("AQ");
    public static final org.apache.axis.types.Token _AG = new org.apache.axis.types.Token("AG");
    public static final org.apache.axis.types.Token _AR = new org.apache.axis.types.Token("AR");
    public static final org.apache.axis.types.Token _AM = new org.apache.axis.types.Token("AM");
    public static final org.apache.axis.types.Token _AW = new org.apache.axis.types.Token("AW");
    public static final org.apache.axis.types.Token _AU = new org.apache.axis.types.Token("AU");
    public static final org.apache.axis.types.Token _AT = new org.apache.axis.types.Token("AT");
    public static final org.apache.axis.types.Token _AZ = new org.apache.axis.types.Token("AZ");
    public static final org.apache.axis.types.Token _BS = new org.apache.axis.types.Token("BS");
    public static final org.apache.axis.types.Token _BH = new org.apache.axis.types.Token("BH");
    public static final org.apache.axis.types.Token _BD = new org.apache.axis.types.Token("BD");
    public static final org.apache.axis.types.Token _BB = new org.apache.axis.types.Token("BB");
    public static final org.apache.axis.types.Token _BY = new org.apache.axis.types.Token("BY");
    public static final org.apache.axis.types.Token _BE = new org.apache.axis.types.Token("BE");
    public static final org.apache.axis.types.Token _BZ = new org.apache.axis.types.Token("BZ");
    public static final org.apache.axis.types.Token _BJ = new org.apache.axis.types.Token("BJ");
    public static final org.apache.axis.types.Token _BM = new org.apache.axis.types.Token("BM");
    public static final org.apache.axis.types.Token _BT = new org.apache.axis.types.Token("BT");
    public static final org.apache.axis.types.Token _BO = new org.apache.axis.types.Token("BO");
    public static final org.apache.axis.types.Token _BA = new org.apache.axis.types.Token("BA");
    public static final org.apache.axis.types.Token _BW = new org.apache.axis.types.Token("BW");
    public static final org.apache.axis.types.Token _BV = new org.apache.axis.types.Token("BV");
    public static final org.apache.axis.types.Token _BR = new org.apache.axis.types.Token("BR");
    public static final org.apache.axis.types.Token _IO = new org.apache.axis.types.Token("IO");
    public static final org.apache.axis.types.Token _BN = new org.apache.axis.types.Token("BN");
    public static final org.apache.axis.types.Token _BG = new org.apache.axis.types.Token("BG");
    public static final org.apache.axis.types.Token _BF = new org.apache.axis.types.Token("BF");
    public static final org.apache.axis.types.Token _BI = new org.apache.axis.types.Token("BI");
    public static final org.apache.axis.types.Token _KH = new org.apache.axis.types.Token("KH");
    public static final org.apache.axis.types.Token _CM = new org.apache.axis.types.Token("CM");
    public static final org.apache.axis.types.Token _CA = new org.apache.axis.types.Token("CA");
    public static final org.apache.axis.types.Token _CV = new org.apache.axis.types.Token("CV");
    public static final org.apache.axis.types.Token _KY = new org.apache.axis.types.Token("KY");
    public static final org.apache.axis.types.Token _CF = new org.apache.axis.types.Token("CF");
    public static final org.apache.axis.types.Token _TD = new org.apache.axis.types.Token("TD");
    public static final org.apache.axis.types.Token _CL = new org.apache.axis.types.Token("CL");
    public static final org.apache.axis.types.Token _C2 = new org.apache.axis.types.Token("C2");
    public static final org.apache.axis.types.Token _CN = new org.apache.axis.types.Token("CN");
    public static final org.apache.axis.types.Token _CX = new org.apache.axis.types.Token("CX");
    public static final org.apache.axis.types.Token _CC = new org.apache.axis.types.Token("CC");
    public static final org.apache.axis.types.Token _CO = new org.apache.axis.types.Token("CO");
    public static final org.apache.axis.types.Token _KM = new org.apache.axis.types.Token("KM");
    public static final org.apache.axis.types.Token _CG = new org.apache.axis.types.Token("CG");
    public static final org.apache.axis.types.Token _CD = new org.apache.axis.types.Token("CD");
    public static final org.apache.axis.types.Token _CK = new org.apache.axis.types.Token("CK");
    public static final org.apache.axis.types.Token _CR = new org.apache.axis.types.Token("CR");
    public static final org.apache.axis.types.Token _CI = new org.apache.axis.types.Token("CI");
    public static final org.apache.axis.types.Token _HR = new org.apache.axis.types.Token("HR");
    public static final org.apache.axis.types.Token _CU = new org.apache.axis.types.Token("CU");
    public static final org.apache.axis.types.Token _CY = new org.apache.axis.types.Token("CY");
    public static final org.apache.axis.types.Token _CZ = new org.apache.axis.types.Token("CZ");
    public static final org.apache.axis.types.Token _DK = new org.apache.axis.types.Token("DK");
    public static final org.apache.axis.types.Token _DJ = new org.apache.axis.types.Token("DJ");
    public static final org.apache.axis.types.Token _DM = new org.apache.axis.types.Token("DM");
    public static final org.apache.axis.types.Token _DO = new org.apache.axis.types.Token("DO");
    public static final org.apache.axis.types.Token _TP = new org.apache.axis.types.Token("TP");
    public static final org.apache.axis.types.Token _EC = new org.apache.axis.types.Token("EC");
    public static final org.apache.axis.types.Token _EG = new org.apache.axis.types.Token("EG");
    public static final org.apache.axis.types.Token _SV = new org.apache.axis.types.Token("SV");
    public static final org.apache.axis.types.Token _GQ = new org.apache.axis.types.Token("GQ");
    public static final org.apache.axis.types.Token _ER = new org.apache.axis.types.Token("ER");
    public static final org.apache.axis.types.Token _EE = new org.apache.axis.types.Token("EE");
    public static final org.apache.axis.types.Token _ET = new org.apache.axis.types.Token("ET");
    public static final org.apache.axis.types.Token _FK = new org.apache.axis.types.Token("FK");
    public static final org.apache.axis.types.Token _FO = new org.apache.axis.types.Token("FO");
    public static final org.apache.axis.types.Token _FJ = new org.apache.axis.types.Token("FJ");
    public static final org.apache.axis.types.Token _FI = new org.apache.axis.types.Token("FI");
    public static final org.apache.axis.types.Token _FR = new org.apache.axis.types.Token("FR");
    public static final org.apache.axis.types.Token _GF = new org.apache.axis.types.Token("GF");
    public static final org.apache.axis.types.Token _PF = new org.apache.axis.types.Token("PF");
    public static final org.apache.axis.types.Token _TF = new org.apache.axis.types.Token("TF");
    public static final org.apache.axis.types.Token _GA = new org.apache.axis.types.Token("GA");
    public static final org.apache.axis.types.Token _GM = new org.apache.axis.types.Token("GM");
    public static final org.apache.axis.types.Token _GE = new org.apache.axis.types.Token("GE");
    public static final org.apache.axis.types.Token _DE = new org.apache.axis.types.Token("DE");
    public static final org.apache.axis.types.Token _GH = new org.apache.axis.types.Token("GH");
    public static final org.apache.axis.types.Token _GI = new org.apache.axis.types.Token("GI");
    public static final org.apache.axis.types.Token _GR = new org.apache.axis.types.Token("GR");
    public static final org.apache.axis.types.Token _GL = new org.apache.axis.types.Token("GL");
    public static final org.apache.axis.types.Token _GD = new org.apache.axis.types.Token("GD");
    public static final org.apache.axis.types.Token _GP = new org.apache.axis.types.Token("GP");
    public static final org.apache.axis.types.Token _GU = new org.apache.axis.types.Token("GU");
    public static final org.apache.axis.types.Token _GT = new org.apache.axis.types.Token("GT");
    public static final org.apache.axis.types.Token _GN = new org.apache.axis.types.Token("GN");
    public static final org.apache.axis.types.Token _GW = new org.apache.axis.types.Token("GW");
    public static final org.apache.axis.types.Token _GY = new org.apache.axis.types.Token("GY");
    public static final org.apache.axis.types.Token _HT = new org.apache.axis.types.Token("HT");
    public static final org.apache.axis.types.Token _HM = new org.apache.axis.types.Token("HM");
    public static final org.apache.axis.types.Token _VA = new org.apache.axis.types.Token("VA");
    public static final org.apache.axis.types.Token _HN = new org.apache.axis.types.Token("HN");
    public static final org.apache.axis.types.Token _HK = new org.apache.axis.types.Token("HK");
    public static final org.apache.axis.types.Token _HU = new org.apache.axis.types.Token("HU");
    public static final org.apache.axis.types.Token _IS = new org.apache.axis.types.Token("IS");
    public static final org.apache.axis.types.Token _IN = new org.apache.axis.types.Token("IN");
    public static final org.apache.axis.types.Token _ID = new org.apache.axis.types.Token("ID");
    public static final org.apache.axis.types.Token _IR = new org.apache.axis.types.Token("IR");
    public static final org.apache.axis.types.Token _IQ = new org.apache.axis.types.Token("IQ");
    public static final org.apache.axis.types.Token _IE = new org.apache.axis.types.Token("IE");
    public static final org.apache.axis.types.Token _IL = new org.apache.axis.types.Token("IL");
    public static final org.apache.axis.types.Token _IT = new org.apache.axis.types.Token("IT");
    public static final org.apache.axis.types.Token _JM = new org.apache.axis.types.Token("JM");
    public static final org.apache.axis.types.Token _JP = new org.apache.axis.types.Token("JP");
    public static final org.apache.axis.types.Token _JO = new org.apache.axis.types.Token("JO");
    public static final org.apache.axis.types.Token _KZ = new org.apache.axis.types.Token("KZ");
    public static final org.apache.axis.types.Token _KE = new org.apache.axis.types.Token("KE");
    public static final org.apache.axis.types.Token _KI = new org.apache.axis.types.Token("KI");
    public static final org.apache.axis.types.Token _KP = new org.apache.axis.types.Token("KP");
    public static final org.apache.axis.types.Token _KR = new org.apache.axis.types.Token("KR");
    public static final org.apache.axis.types.Token _KW = new org.apache.axis.types.Token("KW");
    public static final org.apache.axis.types.Token _KG = new org.apache.axis.types.Token("KG");
    public static final org.apache.axis.types.Token _LA = new org.apache.axis.types.Token("LA");
    public static final org.apache.axis.types.Token _LV = new org.apache.axis.types.Token("LV");
    public static final org.apache.axis.types.Token _LB = new org.apache.axis.types.Token("LB");
    public static final org.apache.axis.types.Token _LS = new org.apache.axis.types.Token("LS");
    public static final org.apache.axis.types.Token _LR = new org.apache.axis.types.Token("LR");
    public static final org.apache.axis.types.Token _LY = new org.apache.axis.types.Token("LY");
    public static final org.apache.axis.types.Token _LI = new org.apache.axis.types.Token("LI");
    public static final org.apache.axis.types.Token _LT = new org.apache.axis.types.Token("LT");
    public static final org.apache.axis.types.Token _LU = new org.apache.axis.types.Token("LU");
    public static final org.apache.axis.types.Token _MO = new org.apache.axis.types.Token("MO");
    public static final org.apache.axis.types.Token _MK = new org.apache.axis.types.Token("MK");
    public static final org.apache.axis.types.Token _MG = new org.apache.axis.types.Token("MG");
    public static final org.apache.axis.types.Token _MW = new org.apache.axis.types.Token("MW");
    public static final org.apache.axis.types.Token _MY = new org.apache.axis.types.Token("MY");
    public static final org.apache.axis.types.Token _MV = new org.apache.axis.types.Token("MV");
    public static final org.apache.axis.types.Token _ML = new org.apache.axis.types.Token("ML");
    public static final org.apache.axis.types.Token _MT = new org.apache.axis.types.Token("MT");
    public static final org.apache.axis.types.Token _MH = new org.apache.axis.types.Token("MH");
    public static final org.apache.axis.types.Token _MQ = new org.apache.axis.types.Token("MQ");
    public static final org.apache.axis.types.Token _MR = new org.apache.axis.types.Token("MR");
    public static final org.apache.axis.types.Token _MU = new org.apache.axis.types.Token("MU");
    public static final org.apache.axis.types.Token _YT = new org.apache.axis.types.Token("YT");
    public static final org.apache.axis.types.Token _MX = new org.apache.axis.types.Token("MX");
    public static final org.apache.axis.types.Token _FM = new org.apache.axis.types.Token("FM");
    public static final org.apache.axis.types.Token _MD = new org.apache.axis.types.Token("MD");
    public static final org.apache.axis.types.Token _MC = new org.apache.axis.types.Token("MC");
    public static final org.apache.axis.types.Token _MN = new org.apache.axis.types.Token("MN");
    public static final org.apache.axis.types.Token _MS = new org.apache.axis.types.Token("MS");
    public static final org.apache.axis.types.Token _MA = new org.apache.axis.types.Token("MA");
    public static final org.apache.axis.types.Token _MZ = new org.apache.axis.types.Token("MZ");
    public static final org.apache.axis.types.Token _MM = new org.apache.axis.types.Token("MM");
    public static final org.apache.axis.types.Token _NA = new org.apache.axis.types.Token("NA");
    public static final org.apache.axis.types.Token _NR = new org.apache.axis.types.Token("NR");
    public static final org.apache.axis.types.Token _NP = new org.apache.axis.types.Token("NP");
    public static final org.apache.axis.types.Token _NL = new org.apache.axis.types.Token("NL");
    public static final org.apache.axis.types.Token _AN = new org.apache.axis.types.Token("AN");
    public static final org.apache.axis.types.Token _NC = new org.apache.axis.types.Token("NC");
    public static final org.apache.axis.types.Token _NZ = new org.apache.axis.types.Token("NZ");
    public static final org.apache.axis.types.Token _NI = new org.apache.axis.types.Token("NI");
    public static final org.apache.axis.types.Token _NE = new org.apache.axis.types.Token("NE");
    public static final org.apache.axis.types.Token _NG = new org.apache.axis.types.Token("NG");
    public static final org.apache.axis.types.Token _NU = new org.apache.axis.types.Token("NU");
    public static final org.apache.axis.types.Token _NF = new org.apache.axis.types.Token("NF");
    public static final org.apache.axis.types.Token _MP = new org.apache.axis.types.Token("MP");
    public static final org.apache.axis.types.Token _NO = new org.apache.axis.types.Token("NO");
    public static final org.apache.axis.types.Token _OM = new org.apache.axis.types.Token("OM");
    public static final org.apache.axis.types.Token _PK = new org.apache.axis.types.Token("PK");
    public static final org.apache.axis.types.Token _PW = new org.apache.axis.types.Token("PW");
    public static final org.apache.axis.types.Token _PS = new org.apache.axis.types.Token("PS");
    public static final org.apache.axis.types.Token _PA = new org.apache.axis.types.Token("PA");
    public static final org.apache.axis.types.Token _PG = new org.apache.axis.types.Token("PG");
    public static final org.apache.axis.types.Token _PY = new org.apache.axis.types.Token("PY");
    public static final org.apache.axis.types.Token _PE = new org.apache.axis.types.Token("PE");
    public static final org.apache.axis.types.Token _PH = new org.apache.axis.types.Token("PH");
    public static final org.apache.axis.types.Token _PN = new org.apache.axis.types.Token("PN");
    public static final org.apache.axis.types.Token _PL = new org.apache.axis.types.Token("PL");
    public static final org.apache.axis.types.Token _PT = new org.apache.axis.types.Token("PT");
    public static final org.apache.axis.types.Token _PR = new org.apache.axis.types.Token("PR");
    public static final org.apache.axis.types.Token _QA = new org.apache.axis.types.Token("QA");
    public static final org.apache.axis.types.Token _RE = new org.apache.axis.types.Token("RE");
    public static final org.apache.axis.types.Token _RO = new org.apache.axis.types.Token("RO");
    public static final org.apache.axis.types.Token _RU = new org.apache.axis.types.Token("RU");
    public static final org.apache.axis.types.Token _RW = new org.apache.axis.types.Token("RW");
    public static final org.apache.axis.types.Token _SH = new org.apache.axis.types.Token("SH");
    public static final org.apache.axis.types.Token _KN = new org.apache.axis.types.Token("KN");
    public static final org.apache.axis.types.Token _LC = new org.apache.axis.types.Token("LC");
    public static final org.apache.axis.types.Token _PM = new org.apache.axis.types.Token("PM");
    public static final org.apache.axis.types.Token _VC = new org.apache.axis.types.Token("VC");
    public static final org.apache.axis.types.Token _WS = new org.apache.axis.types.Token("WS");
    public static final org.apache.axis.types.Token _SM = new org.apache.axis.types.Token("SM");
    public static final org.apache.axis.types.Token _ST = new org.apache.axis.types.Token("ST");
    public static final org.apache.axis.types.Token _SA = new org.apache.axis.types.Token("SA");
    public static final org.apache.axis.types.Token _SN = new org.apache.axis.types.Token("SN");
    public static final org.apache.axis.types.Token _SC = new org.apache.axis.types.Token("SC");
    public static final org.apache.axis.types.Token _SL = new org.apache.axis.types.Token("SL");
    public static final org.apache.axis.types.Token _SG = new org.apache.axis.types.Token("SG");
    public static final org.apache.axis.types.Token _SK = new org.apache.axis.types.Token("SK");
    public static final org.apache.axis.types.Token _SI = new org.apache.axis.types.Token("SI");
    public static final org.apache.axis.types.Token _SB = new org.apache.axis.types.Token("SB");
    public static final org.apache.axis.types.Token _SO = new org.apache.axis.types.Token("SO");
    public static final org.apache.axis.types.Token _ZA = new org.apache.axis.types.Token("ZA");
    public static final org.apache.axis.types.Token _GS = new org.apache.axis.types.Token("GS");
    public static final org.apache.axis.types.Token _ES = new org.apache.axis.types.Token("ES");
    public static final org.apache.axis.types.Token _LK = new org.apache.axis.types.Token("LK");
    public static final org.apache.axis.types.Token _SD = new org.apache.axis.types.Token("SD");
    public static final org.apache.axis.types.Token _SR = new org.apache.axis.types.Token("SR");
    public static final org.apache.axis.types.Token _SJ = new org.apache.axis.types.Token("SJ");
    public static final org.apache.axis.types.Token _SZ = new org.apache.axis.types.Token("SZ");
    public static final org.apache.axis.types.Token _SE = new org.apache.axis.types.Token("SE");
    public static final org.apache.axis.types.Token _CH = new org.apache.axis.types.Token("CH");
    public static final org.apache.axis.types.Token _SY = new org.apache.axis.types.Token("SY");
    public static final org.apache.axis.types.Token _TW = new org.apache.axis.types.Token("TW");
    public static final org.apache.axis.types.Token _TJ = new org.apache.axis.types.Token("TJ");
    public static final org.apache.axis.types.Token _TZ = new org.apache.axis.types.Token("TZ");
    public static final org.apache.axis.types.Token _TH = new org.apache.axis.types.Token("TH");
    public static final org.apache.axis.types.Token _TG = new org.apache.axis.types.Token("TG");
    public static final org.apache.axis.types.Token _TK = new org.apache.axis.types.Token("TK");
    public static final org.apache.axis.types.Token _TO = new org.apache.axis.types.Token("TO");
    public static final org.apache.axis.types.Token _TT = new org.apache.axis.types.Token("TT");
    public static final org.apache.axis.types.Token _TN = new org.apache.axis.types.Token("TN");
    public static final org.apache.axis.types.Token _TR = new org.apache.axis.types.Token("TR");
    public static final org.apache.axis.types.Token _TM = new org.apache.axis.types.Token("TM");
    public static final org.apache.axis.types.Token _TC = new org.apache.axis.types.Token("TC");
    public static final org.apache.axis.types.Token _TV = new org.apache.axis.types.Token("TV");
    public static final org.apache.axis.types.Token _UG = new org.apache.axis.types.Token("UG");
    public static final org.apache.axis.types.Token _UA = new org.apache.axis.types.Token("UA");
    public static final org.apache.axis.types.Token _AE = new org.apache.axis.types.Token("AE");
    public static final org.apache.axis.types.Token _GB = new org.apache.axis.types.Token("GB");
    public static final org.apache.axis.types.Token _US = new org.apache.axis.types.Token("US");
    public static final org.apache.axis.types.Token _UM = new org.apache.axis.types.Token("UM");
    public static final org.apache.axis.types.Token _UY = new org.apache.axis.types.Token("UY");
    public static final org.apache.axis.types.Token _UZ = new org.apache.axis.types.Token("UZ");
    public static final org.apache.axis.types.Token _VU = new org.apache.axis.types.Token("VU");
    public static final org.apache.axis.types.Token _VE = new org.apache.axis.types.Token("VE");
    public static final org.apache.axis.types.Token _VN = new org.apache.axis.types.Token("VN");
    public static final org.apache.axis.types.Token _VG = new org.apache.axis.types.Token("VG");
    public static final org.apache.axis.types.Token _VI = new org.apache.axis.types.Token("VI");
    public static final org.apache.axis.types.Token _WF = new org.apache.axis.types.Token("WF");
    public static final org.apache.axis.types.Token _EH = new org.apache.axis.types.Token("EH");
    public static final org.apache.axis.types.Token _YE = new org.apache.axis.types.Token("YE");
    public static final org.apache.axis.types.Token _YU = new org.apache.axis.types.Token("YU");
    public static final org.apache.axis.types.Token _ZM = new org.apache.axis.types.Token("ZM");
    public static final org.apache.axis.types.Token _ZW = new org.apache.axis.types.Token("ZW");
    public static final org.apache.axis.types.Token _AA = new org.apache.axis.types.Token("AA");
    public static final org.apache.axis.types.Token _QM = new org.apache.axis.types.Token("QM");
    public static final org.apache.axis.types.Token _QN = new org.apache.axis.types.Token("QN");
    public static final org.apache.axis.types.Token _QO = new org.apache.axis.types.Token("QO");
    public static final org.apache.axis.types.Token _QP = new org.apache.axis.types.Token("QP");
    public static final org.apache.axis.types.Token _CS = new org.apache.axis.types.Token("CS");
    public static final org.apache.axis.types.Token _CustomCode = new org.apache.axis.types.Token("CustomCode");
    public static final org.apache.axis.types.Token _GG = new org.apache.axis.types.Token("GG");
    public static final org.apache.axis.types.Token _IM = new org.apache.axis.types.Token("IM");
    public static final org.apache.axis.types.Token _JE = new org.apache.axis.types.Token("JE");
    public static final org.apache.axis.types.Token _TL = new org.apache.axis.types.Token("TL");
    public static final org.apache.axis.types.Token _RS = new org.apache.axis.types.Token("RS");
    public static final org.apache.axis.types.Token _ME = new org.apache.axis.types.Token("ME");
    public static final CountryCodeType AF = new CountryCodeType(_AF);
    public static final CountryCodeType AL = new CountryCodeType(_AL);
    public static final CountryCodeType DZ = new CountryCodeType(_DZ);
    public static final CountryCodeType AS = new CountryCodeType(_AS);
    public static final CountryCodeType AD = new CountryCodeType(_AD);
    public static final CountryCodeType AO = new CountryCodeType(_AO);
    public static final CountryCodeType AI = new CountryCodeType(_AI);
    public static final CountryCodeType AQ = new CountryCodeType(_AQ);
    public static final CountryCodeType AG = new CountryCodeType(_AG);
    public static final CountryCodeType AR = new CountryCodeType(_AR);
    public static final CountryCodeType AM = new CountryCodeType(_AM);
    public static final CountryCodeType AW = new CountryCodeType(_AW);
    public static final CountryCodeType AU = new CountryCodeType(_AU);
    public static final CountryCodeType AT = new CountryCodeType(_AT);
    public static final CountryCodeType AZ = new CountryCodeType(_AZ);
    public static final CountryCodeType BS = new CountryCodeType(_BS);
    public static final CountryCodeType BH = new CountryCodeType(_BH);
    public static final CountryCodeType BD = new CountryCodeType(_BD);
    public static final CountryCodeType BB = new CountryCodeType(_BB);
    public static final CountryCodeType BY = new CountryCodeType(_BY);
    public static final CountryCodeType BE = new CountryCodeType(_BE);
    public static final CountryCodeType BZ = new CountryCodeType(_BZ);
    public static final CountryCodeType BJ = new CountryCodeType(_BJ);
    public static final CountryCodeType BM = new CountryCodeType(_BM);
    public static final CountryCodeType BT = new CountryCodeType(_BT);
    public static final CountryCodeType BO = new CountryCodeType(_BO);
    public static final CountryCodeType BA = new CountryCodeType(_BA);
    public static final CountryCodeType BW = new CountryCodeType(_BW);
    public static final CountryCodeType BV = new CountryCodeType(_BV);
    public static final CountryCodeType BR = new CountryCodeType(_BR);
    public static final CountryCodeType IO = new CountryCodeType(_IO);
    public static final CountryCodeType BN = new CountryCodeType(_BN);
    public static final CountryCodeType BG = new CountryCodeType(_BG);
    public static final CountryCodeType BF = new CountryCodeType(_BF);
    public static final CountryCodeType BI = new CountryCodeType(_BI);
    public static final CountryCodeType KH = new CountryCodeType(_KH);
    public static final CountryCodeType CM = new CountryCodeType(_CM);
    public static final CountryCodeType CA = new CountryCodeType(_CA);
    public static final CountryCodeType CV = new CountryCodeType(_CV);
    public static final CountryCodeType KY = new CountryCodeType(_KY);
    public static final CountryCodeType CF = new CountryCodeType(_CF);
    public static final CountryCodeType TD = new CountryCodeType(_TD);
    public static final CountryCodeType CL = new CountryCodeType(_CL);
    public static final CountryCodeType C2 = new CountryCodeType(_C2);
    public static final CountryCodeType CN = new CountryCodeType(_CN);
    public static final CountryCodeType CX = new CountryCodeType(_CX);
    public static final CountryCodeType CC = new CountryCodeType(_CC);
    public static final CountryCodeType CO = new CountryCodeType(_CO);
    public static final CountryCodeType KM = new CountryCodeType(_KM);
    public static final CountryCodeType CG = new CountryCodeType(_CG);
    public static final CountryCodeType CD = new CountryCodeType(_CD);
    public static final CountryCodeType CK = new CountryCodeType(_CK);
    public static final CountryCodeType CR = new CountryCodeType(_CR);
    public static final CountryCodeType CI = new CountryCodeType(_CI);
    public static final CountryCodeType HR = new CountryCodeType(_HR);
    public static final CountryCodeType CU = new CountryCodeType(_CU);
    public static final CountryCodeType CY = new CountryCodeType(_CY);
    public static final CountryCodeType CZ = new CountryCodeType(_CZ);
    public static final CountryCodeType DK = new CountryCodeType(_DK);
    public static final CountryCodeType DJ = new CountryCodeType(_DJ);
    public static final CountryCodeType DM = new CountryCodeType(_DM);
    public static final CountryCodeType DO = new CountryCodeType(_DO);
    public static final CountryCodeType TP = new CountryCodeType(_TP);
    public static final CountryCodeType EC = new CountryCodeType(_EC);
    public static final CountryCodeType EG = new CountryCodeType(_EG);
    public static final CountryCodeType SV = new CountryCodeType(_SV);
    public static final CountryCodeType GQ = new CountryCodeType(_GQ);
    public static final CountryCodeType ER = new CountryCodeType(_ER);
    public static final CountryCodeType EE = new CountryCodeType(_EE);
    public static final CountryCodeType ET = new CountryCodeType(_ET);
    public static final CountryCodeType FK = new CountryCodeType(_FK);
    public static final CountryCodeType FO = new CountryCodeType(_FO);
    public static final CountryCodeType FJ = new CountryCodeType(_FJ);
    public static final CountryCodeType FI = new CountryCodeType(_FI);
    public static final CountryCodeType FR = new CountryCodeType(_FR);
    public static final CountryCodeType GF = new CountryCodeType(_GF);
    public static final CountryCodeType PF = new CountryCodeType(_PF);
    public static final CountryCodeType TF = new CountryCodeType(_TF);
    public static final CountryCodeType GA = new CountryCodeType(_GA);
    public static final CountryCodeType GM = new CountryCodeType(_GM);
    public static final CountryCodeType GE = new CountryCodeType(_GE);
    public static final CountryCodeType DE = new CountryCodeType(_DE);
    public static final CountryCodeType GH = new CountryCodeType(_GH);
    public static final CountryCodeType GI = new CountryCodeType(_GI);
    public static final CountryCodeType GR = new CountryCodeType(_GR);
    public static final CountryCodeType GL = new CountryCodeType(_GL);
    public static final CountryCodeType GD = new CountryCodeType(_GD);
    public static final CountryCodeType GP = new CountryCodeType(_GP);
    public static final CountryCodeType GU = new CountryCodeType(_GU);
    public static final CountryCodeType GT = new CountryCodeType(_GT);
    public static final CountryCodeType GN = new CountryCodeType(_GN);
    public static final CountryCodeType GW = new CountryCodeType(_GW);
    public static final CountryCodeType GY = new CountryCodeType(_GY);
    public static final CountryCodeType HT = new CountryCodeType(_HT);
    public static final CountryCodeType HM = new CountryCodeType(_HM);
    public static final CountryCodeType VA = new CountryCodeType(_VA);
    public static final CountryCodeType HN = new CountryCodeType(_HN);
    public static final CountryCodeType HK = new CountryCodeType(_HK);
    public static final CountryCodeType HU = new CountryCodeType(_HU);
    public static final CountryCodeType IS = new CountryCodeType(_IS);
    public static final CountryCodeType IN = new CountryCodeType(_IN);
    public static final CountryCodeType ID = new CountryCodeType(_ID);
    public static final CountryCodeType IR = new CountryCodeType(_IR);
    public static final CountryCodeType IQ = new CountryCodeType(_IQ);
    public static final CountryCodeType IE = new CountryCodeType(_IE);
    public static final CountryCodeType IL = new CountryCodeType(_IL);
    public static final CountryCodeType IT = new CountryCodeType(_IT);
    public static final CountryCodeType JM = new CountryCodeType(_JM);
    public static final CountryCodeType JP = new CountryCodeType(_JP);
    public static final CountryCodeType JO = new CountryCodeType(_JO);
    public static final CountryCodeType KZ = new CountryCodeType(_KZ);
    public static final CountryCodeType KE = new CountryCodeType(_KE);
    public static final CountryCodeType KI = new CountryCodeType(_KI);
    public static final CountryCodeType KP = new CountryCodeType(_KP);
    public static final CountryCodeType KR = new CountryCodeType(_KR);
    public static final CountryCodeType KW = new CountryCodeType(_KW);
    public static final CountryCodeType KG = new CountryCodeType(_KG);
    public static final CountryCodeType LA = new CountryCodeType(_LA);
    public static final CountryCodeType LV = new CountryCodeType(_LV);
    public static final CountryCodeType LB = new CountryCodeType(_LB);
    public static final CountryCodeType LS = new CountryCodeType(_LS);
    public static final CountryCodeType LR = new CountryCodeType(_LR);
    public static final CountryCodeType LY = new CountryCodeType(_LY);
    public static final CountryCodeType LI = new CountryCodeType(_LI);
    public static final CountryCodeType LT = new CountryCodeType(_LT);
    public static final CountryCodeType LU = new CountryCodeType(_LU);
    public static final CountryCodeType MO = new CountryCodeType(_MO);
    public static final CountryCodeType MK = new CountryCodeType(_MK);
    public static final CountryCodeType MG = new CountryCodeType(_MG);
    public static final CountryCodeType MW = new CountryCodeType(_MW);
    public static final CountryCodeType MY = new CountryCodeType(_MY);
    public static final CountryCodeType MV = new CountryCodeType(_MV);
    public static final CountryCodeType ML = new CountryCodeType(_ML);
    public static final CountryCodeType MT = new CountryCodeType(_MT);
    public static final CountryCodeType MH = new CountryCodeType(_MH);
    public static final CountryCodeType MQ = new CountryCodeType(_MQ);
    public static final CountryCodeType MR = new CountryCodeType(_MR);
    public static final CountryCodeType MU = new CountryCodeType(_MU);
    public static final CountryCodeType YT = new CountryCodeType(_YT);
    public static final CountryCodeType MX = new CountryCodeType(_MX);
    public static final CountryCodeType FM = new CountryCodeType(_FM);
    public static final CountryCodeType MD = new CountryCodeType(_MD);
    public static final CountryCodeType MC = new CountryCodeType(_MC);
    public static final CountryCodeType MN = new CountryCodeType(_MN);
    public static final CountryCodeType MS = new CountryCodeType(_MS);
    public static final CountryCodeType MA = new CountryCodeType(_MA);
    public static final CountryCodeType MZ = new CountryCodeType(_MZ);
    public static final CountryCodeType MM = new CountryCodeType(_MM);
    public static final CountryCodeType NA = new CountryCodeType(_NA);
    public static final CountryCodeType NR = new CountryCodeType(_NR);
    public static final CountryCodeType NP = new CountryCodeType(_NP);
    public static final CountryCodeType NL = new CountryCodeType(_NL);
    public static final CountryCodeType AN = new CountryCodeType(_AN);
    public static final CountryCodeType NC = new CountryCodeType(_NC);
    public static final CountryCodeType NZ = new CountryCodeType(_NZ);
    public static final CountryCodeType NI = new CountryCodeType(_NI);
    public static final CountryCodeType NE = new CountryCodeType(_NE);
    public static final CountryCodeType NG = new CountryCodeType(_NG);
    public static final CountryCodeType NU = new CountryCodeType(_NU);
    public static final CountryCodeType NF = new CountryCodeType(_NF);
    public static final CountryCodeType MP = new CountryCodeType(_MP);
    public static final CountryCodeType NO = new CountryCodeType(_NO);
    public static final CountryCodeType OM = new CountryCodeType(_OM);
    public static final CountryCodeType PK = new CountryCodeType(_PK);
    public static final CountryCodeType PW = new CountryCodeType(_PW);
    public static final CountryCodeType PS = new CountryCodeType(_PS);
    public static final CountryCodeType PA = new CountryCodeType(_PA);
    public static final CountryCodeType PG = new CountryCodeType(_PG);
    public static final CountryCodeType PY = new CountryCodeType(_PY);
    public static final CountryCodeType PE = new CountryCodeType(_PE);
    public static final CountryCodeType PH = new CountryCodeType(_PH);
    public static final CountryCodeType PN = new CountryCodeType(_PN);
    public static final CountryCodeType PL = new CountryCodeType(_PL);
    public static final CountryCodeType PT = new CountryCodeType(_PT);
    public static final CountryCodeType PR = new CountryCodeType(_PR);
    public static final CountryCodeType QA = new CountryCodeType(_QA);
    public static final CountryCodeType RE = new CountryCodeType(_RE);
    public static final CountryCodeType RO = new CountryCodeType(_RO);
    public static final CountryCodeType RU = new CountryCodeType(_RU);
    public static final CountryCodeType RW = new CountryCodeType(_RW);
    public static final CountryCodeType SH = new CountryCodeType(_SH);
    public static final CountryCodeType KN = new CountryCodeType(_KN);
    public static final CountryCodeType LC = new CountryCodeType(_LC);
    public static final CountryCodeType PM = new CountryCodeType(_PM);
    public static final CountryCodeType VC = new CountryCodeType(_VC);
    public static final CountryCodeType WS = new CountryCodeType(_WS);
    public static final CountryCodeType SM = new CountryCodeType(_SM);
    public static final CountryCodeType ST = new CountryCodeType(_ST);
    public static final CountryCodeType SA = new CountryCodeType(_SA);
    public static final CountryCodeType SN = new CountryCodeType(_SN);
    public static final CountryCodeType SC = new CountryCodeType(_SC);
    public static final CountryCodeType SL = new CountryCodeType(_SL);
    public static final CountryCodeType SG = new CountryCodeType(_SG);
    public static final CountryCodeType SK = new CountryCodeType(_SK);
    public static final CountryCodeType SI = new CountryCodeType(_SI);
    public static final CountryCodeType SB = new CountryCodeType(_SB);
    public static final CountryCodeType SO = new CountryCodeType(_SO);
    public static final CountryCodeType ZA = new CountryCodeType(_ZA);
    public static final CountryCodeType GS = new CountryCodeType(_GS);
    public static final CountryCodeType ES = new CountryCodeType(_ES);
    public static final CountryCodeType LK = new CountryCodeType(_LK);
    public static final CountryCodeType SD = new CountryCodeType(_SD);
    public static final CountryCodeType SR = new CountryCodeType(_SR);
    public static final CountryCodeType SJ = new CountryCodeType(_SJ);
    public static final CountryCodeType SZ = new CountryCodeType(_SZ);
    public static final CountryCodeType SE = new CountryCodeType(_SE);
    public static final CountryCodeType CH = new CountryCodeType(_CH);
    public static final CountryCodeType SY = new CountryCodeType(_SY);
    public static final CountryCodeType TW = new CountryCodeType(_TW);
    public static final CountryCodeType TJ = new CountryCodeType(_TJ);
    public static final CountryCodeType TZ = new CountryCodeType(_TZ);
    public static final CountryCodeType TH = new CountryCodeType(_TH);
    public static final CountryCodeType TG = new CountryCodeType(_TG);
    public static final CountryCodeType TK = new CountryCodeType(_TK);
    public static final CountryCodeType TO = new CountryCodeType(_TO);
    public static final CountryCodeType TT = new CountryCodeType(_TT);
    public static final CountryCodeType TN = new CountryCodeType(_TN);
    public static final CountryCodeType TR = new CountryCodeType(_TR);
    public static final CountryCodeType TM = new CountryCodeType(_TM);
    public static final CountryCodeType TC = new CountryCodeType(_TC);
    public static final CountryCodeType TV = new CountryCodeType(_TV);
    public static final CountryCodeType UG = new CountryCodeType(_UG);
    public static final CountryCodeType UA = new CountryCodeType(_UA);
    public static final CountryCodeType AE = new CountryCodeType(_AE);
    public static final CountryCodeType GB = new CountryCodeType(_GB);
    public static final CountryCodeType US = new CountryCodeType(_US);
    public static final CountryCodeType UM = new CountryCodeType(_UM);
    public static final CountryCodeType UY = new CountryCodeType(_UY);
    public static final CountryCodeType UZ = new CountryCodeType(_UZ);
    public static final CountryCodeType VU = new CountryCodeType(_VU);
    public static final CountryCodeType VE = new CountryCodeType(_VE);
    public static final CountryCodeType VN = new CountryCodeType(_VN);
    public static final CountryCodeType VG = new CountryCodeType(_VG);
    public static final CountryCodeType VI = new CountryCodeType(_VI);
    public static final CountryCodeType WF = new CountryCodeType(_WF);
    public static final CountryCodeType EH = new CountryCodeType(_EH);
    public static final CountryCodeType YE = new CountryCodeType(_YE);
    public static final CountryCodeType YU = new CountryCodeType(_YU);
    public static final CountryCodeType ZM = new CountryCodeType(_ZM);
    public static final CountryCodeType ZW = new CountryCodeType(_ZW);
    public static final CountryCodeType AA = new CountryCodeType(_AA);
    public static final CountryCodeType QM = new CountryCodeType(_QM);
    public static final CountryCodeType QN = new CountryCodeType(_QN);
    public static final CountryCodeType QO = new CountryCodeType(_QO);
    public static final CountryCodeType QP = new CountryCodeType(_QP);
    public static final CountryCodeType CS = new CountryCodeType(_CS);
    public static final CountryCodeType CustomCode = new CountryCodeType(_CustomCode);
    public static final CountryCodeType GG = new CountryCodeType(_GG);
    public static final CountryCodeType IM = new CountryCodeType(_IM);
    public static final CountryCodeType JE = new CountryCodeType(_JE);
    public static final CountryCodeType TL = new CountryCodeType(_TL);
    public static final CountryCodeType RS = new CountryCodeType(_RS);
    public static final CountryCodeType ME = new CountryCodeType(_ME);
    public org.apache.axis.types.Token getValue() { return _value_;}
    public static CountryCodeType fromValue(org.apache.axis.types.Token value)
          throws java.lang.IllegalArgumentException {
        CountryCodeType enumeration = (CountryCodeType)
            _table_.get(value);
        if (enumeration==null) throw new java.lang.IllegalArgumentException();
        return enumeration;
    }
    public static CountryCodeType fromString(java.lang.String value)
          throws java.lang.IllegalArgumentException {
        try {
            return fromValue(new org.apache.axis.types.Token(value));
        } catch (Exception e) {
            throw new java.lang.IllegalArgumentException();
        }
    }
    public boolean equals(java.lang.Object obj) {return (obj == this);}
    public int hashCode() { return toString().hashCode();}
    public java.lang.String toString() { return _value_.toString();}
    public java.lang.Object readResolve() throws java.io.ObjectStreamException { return fromValue(_value_);}
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumSerializer(
            _javaType, _xmlType);
    }
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new org.apache.axis.encoding.ser.EnumDeserializer(
            _javaType, _xmlType);
    }
    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(CountryCodeType.class);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("urn:ebay:apis:eBLBaseComponents", "CountryCodeType"));
    }
    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

}
